import os
import uuid
from fastapi import APIRouter, BackgroundTasks
from fastapi.responses import FileResponse
from pydantic import BaseModel
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from models.schemas import StandardResponse
from services.state import get_task

router = APIRouter()

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "..", "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

class OutputRequest(BaseModel):
    task_id: str
    format: str

def _generate_pdf(task_id: str) -> str:
    """Generate a real PDF report from research results."""
    task = get_task(task_id)
    if not task:
        return None
    
    file_path = os.path.join(REPORTS_DIR, f"{task_id}.pdf")
    doc = SimpleDocTemplate(file_path, pagesize=letter, 
                            topMargin=0.75*inch, bottomMargin=0.75*inch,
                            leftMargin=0.75*inch, rightMargin=0.75*inch)
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle('CustomTitle', parent=styles['Title'],
                                  fontSize=22, textColor=HexColor('#00f3ff'),
                                  spaceAfter=20)
    heading_style = ParagraphStyle('CustomHeading', parent=styles['Heading2'],
                                    fontSize=14, textColor=HexColor('#9d00ff'),
                                    spaceAfter=10, spaceBefore=20)
    body_style = ParagraphStyle('CustomBody', parent=styles['Normal'],
                                 fontSize=11, leading=16, spaceAfter=8)
    meta_style = ParagraphStyle('Meta', parent=styles['Normal'],
                                 fontSize=9, textColor=HexColor('#888888'), spaceAfter=15)
    
    elements = []
    
    # Title
    elements.append(Paragraph("ResearchX AI — Intelligence Report", title_style))
    elements.append(Paragraph(f"Query: {task['query']}", meta_style))
    elements.append(Paragraph(f"Generated: {task['created_at']} | Task ID: {task_id[:8]}...", meta_style))
    elements.append(Spacer(1, 20))
    
    # Strategy
    strategy = task.get("strategy", [])
    if strategy:
        elements.append(Paragraph("Research Strategy", heading_style))
        for step in strategy:
            elements.append(Paragraph(f"<b>Step {step.get('id', '?')}:</b> {step.get('action', '')} — {step.get('description', '')}", body_style))
        elements.append(Spacer(1, 10))
    
    # Results
    results = task.get("results", {})
    if results:
        elements.append(Paragraph("Key Findings", heading_style))
        if results.get("summary"):
            elements.append(Paragraph(results["summary"], body_style))
        findings = results.get("key_findings", [])
        for i, f in enumerate(findings, 1):
            elements.append(Paragraph(f"  {i}. {f}", body_style))
        elements.append(Spacer(1, 10))
    
    # Deep Dive
    deep_dive = task.get("deep_dive", {})
    if deep_dive:
        elements.append(Paragraph("Deep Dive Analysis", heading_style))
        if deep_dive.get("content"):
            elements.append(Paragraph(deep_dive["content"], body_style))
        citations = deep_dive.get("citations", [])
        if citations:
            elements.append(Paragraph("Citations", heading_style))
            for c in citations:
                elements.append(Paragraph(f"• {c}", body_style))
    
    # Footer
    elements.append(Spacer(1, 30))
    elements.append(Paragraph("— Generated by ResearchX AI Platform —", meta_style))
    
    doc.build(elements)
    return file_path

@router.post("/generate", response_model=StandardResponse[dict], summary="Trigger Output Pipeline")
async def generate_output(request: OutputRequest):
    """Generate a downloadable report based on the research results."""
    file_path = _generate_pdf(request.task_id)
    if not file_path:
        return StandardResponse(success=False, error="Task not found or results not ready")
    
    return StandardResponse(success=True, data={
        "status": "Report generated",
        "file_id": request.task_id,
        "format": request.format,
        "download_url": f"/api/output/download/{request.task_id}"
    })

@router.get("/download/{file_id}", summary="Download compiled docs")
async def download_report(file_id: str):
    """Download the generated PDF."""
    file_path = os.path.join(REPORTS_DIR, f"{file_id}.pdf")
    if os.path.exists(file_path):
        return FileResponse(file_path, 
                          filename=f"ResearchX_Report_{file_id[:8]}.pdf",
                          media_type="application/pdf")
    return StandardResponse(success=False, error="Report not found")
